### ISSUE TITLE
cargo build --release //error

### ISSUE THREAD

**Issue by goiltpatpat** [clover-network/clover#14]
error[E0425]: cannot find value CHAIN_ID in this scope
     --> /mnt/c/Users/..../clover/runtime/src/lib.rs:384:28
      |
  384 |   pub const ChainId: u64 = CHAIN_ID;
      |                            ^^^^^^^^ not found in this scope

  error: aborting due to previous error

  For more information about this error, try rustc --explain E0425.
  error: could not compile clover-runtime

  To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

How to ifx ?

**Comment by pangwa** [comment]
`cargo build --features clover-testnet`
