### ISSUE TITLE
node say like this

### ISSUE THREAD

**Issue by goiltpatpat** [clover-network/clover#15]
this problem or not ?
Verification failed for block 0x26f071d875dff16a0b2ac9aecc661f79cf7af2014d410744e786ad8fccd27ff4 received from peer: 12D3KooWDDG2xjeEJ827tzb7WiwgBF5mx6Ygz1RxTYDg1B14iauj, "Header 0x26f071d875dff16a0b2ac9aecc661f79cf7af2014d410744e786ad8fccd27ff4 rejected: too far in the future"

**Comment by pangwa** [comment]
Please provide more information, e.g. how you setup your node? The branch/commit you're using?

**Comment by goiltpatpat** [comment]
> Please provide more information, e.g. how you setup your node? The branch/commit you're using?

this
./target/release/clover --chain specs/clover-preview-iris.json --port 30333 --ws-port 9944 --rpc-port 9933  --name PatYagami --rpc-cors=all --rpc-methods=Unsafe --validator --unsafe-ws-external --unsafe-rpc-external

**Comment by pangwa** [comment]
purge your chain data first and restart the code.

**Comment by goiltpatpat** [comment]
> purge your chain data first and restart the code.
excuse me,
how to purge chain data ?

**Comment by goiltpatpat** [comment]
Verification failed for block 0x17e1dfadd780cfcfbfca929be618fa7ae92cd8effb25e03d340d9aa0e3fe472a received from peer: 12D3KooW9tuXWjk95YJkKM7KSzoGNBpdMqDi4qB8JUXnKrYiwwAU, "Header 0x17e1dfadd780cfcfbfca929be618fa7ae92cd8effb25e03d340d9aa0e3fe472a rejected: too far in the future"

fail same

**Comment by pangwa** [comment]
This looks like to be an environment issue. Please check your system time, time zone etc. It's not related to the code.
