### ISSUE TITLE
out-of-box build fails

### ISSUE THREAD

**Issue by matthewaerose** [clover-network/clover#32]
**Description**

_Tell us what happened. In particular, be specific about any changes you made to this template.
Ideally, provide a link to your project's GitHub repository. Please note that we are not able to
support all conceivable changes to this template project, but the more information you are able to
provide the more equipped we will be to help._

Following steps from [this page](https://docs.clover.finance/quick-start/local-node/setting-up-a-node) fails 2 ways.
**first way**
running `scripts/init.sh` fails with a number of rust errors, most of which are `error[E0658]: const generics are unstable`.
This can be overcome by using the latest nightly of rust instead of the specified version in `init.sh`

**second way**
Using the latest nightly of rust, running `cargo build --release` gives us the error:
```
error: failed to download `parity-db v0.2.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/mattrose/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11	` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
```

This can be overcome with `cargo update -p parity-db` to update parity-db to latest version.
Additional failures continue with substrate libs, of which there are too many to fix/update.

Any help getting a node up and running would be appreciated.

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. Go to this link https://docs.clover.finance/quick-start/local-node/setting-up-a-node
2. Try to run step 3, assuming you have pre-requisite software installed
3. See errors mentioned above

**Expected vs. Actual Behavior**
Expected - clover would build and I could run a local node
Actual - a bunch of errors and clover did not build

**Environment**

_Describe the environment in which you encountered this bug. Use the` list below as a starting point
and add additional information if you think it's relevant._

- Operating system:
  - `uname -a` -> `Linux 5.7.0+ #1 SMP Sun Nov 29 20:42:36 CST 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Template version/tag:
- Rust version (run `rustup show`): tried `nightly-x86_64-unknown-linux-gnu` and `nightly-2020-09-25-x86_64-unknown-linux-gnu`, the one set by `init.sh`. Neither worked.

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._
Errors listed earlier.

**Additional Information**

_Please add any other details that you think may help us solve your problem._
Update substrate and clover dependencies to match

**Comment by gilescope** [comment]
Rather than importing substrate with `tag="v3.0.0"` it needs a later version of substrate: `branch="polkadot-v0.9.9"` or probably better to choose `branch="polkadot-v0.9.10"`.

If you want to do this PR feel free to @ me if you get stuck. I know a few libs have moved from sp_ to sc_ in terms of renames as we've been putting a few crates in better locations.

**Comment by matthewaerose** [comment]
Did some more poking around and this seems to happen with develop. Building master worked fine, still needed to use flags from #8 to get `CHAIN_ID`, as well as get around 'virtual workspace'.

Let me know if you'd want to pursue the fixes you were talking about, @gilescope

**Comment by pangwa** [comment]
#34 should fix the build error, this is caused by a bad depencency(parity-db).
