### ISSUE TITLE
add types package in @polkadot/apps-config

### ISSUE THREAD

**Issue by Ljzn** [clover-network/clover#46]
Hi, clover team. Maybe here is not the right place, but would you like to add types package of Clover in @polkadot/apps-config, so we can have the sidecar support.

https://github.com/paritytech/substrate-api-sidecar/issues/825#issuecomment-1021821595

**Comment by pangwa** [comment]
https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/clover.ts . It's already there.

**Comment by pangwa** [comment]
upstream confirms resolved.
