### ISSUE TITLE
Sakura node RPC endpoint

### ISSUE THREAD

**Issue by isSerge** [clover-network/clover#47]
Hi guys, I am trying to connect to Sakura node using `wss://api-sakura.clover.finance`, but it does not work. Are there any other endpoints available? Thanks

**Comment by pangwa** [comment]
Have you tried `wss://rpc.sakura.clover.finance` ?

**Comment by isSerge** [comment]
I did not, because it's not listed on polkadot/apps. It seems to work for me, thanks. Would be great if you could make it public.
