### ISSUE TITLE
Build failed with `CHAIN_ID` error

### ISSUE THREAD

**Issue by kvrvgixzis** [clover-network/clover#8]
```bash
 error[E0425]: cannot find value `CHAIN_ID` in this scope
     --> /home/nkt/git/clover/runtime/src/lib.rs:383:28
      |
  383 |   pub const ChainId: u64 = CHAIN_ID;
      |                            ^^^^^^^^ not found in this scope

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0425`.
  error: could not compile `clover-runtime`

  To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...

```

**Comment by pangwa** [comment]
Latest code requires a clover-testnet/clover-mainnet feature flag. 

You can build it with "cargo build --release --features clover-testnet" .

**Comment by maflohr** [comment]
If you are trying to build with the rustc nightly channel, you might encounter the following error when adding the `--features clover-testnet` flag:

`error: --features is not allowed in the root of a virtual workspace
note: while this was previously accepted, it didn't actually do anything`

Adding `-Z package-features` should work in that case:

`cargo build --release --features clover-testnet -Z package-features`

**Comment by goiltpatpat** [comment]
> If you are trying to build with the rustc nightly channel, you might encounter the following error when adding the `--features clover-testnet` flag:
> 
> `error: --features is not allowed in the root of a virtual workspace note: while this was previously accepted, it didn't actually do anything`
> 
> Adding `-Z package-features` should work in that case:
> 
> `cargo build --release --features clover-testnet -Z package-features`

thx so much
