### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by mans25-stack** [clover-network/clover#9]
Context: Determine the latest version of the Clover binary (you can see the latest releases here: https://github.com/clover-network/clover/releases)
curl -sL https://github.com/clover-network/clover/releases/download/*VERSION*/clover-o clover

The release folder is not found, and hence version cannot be located. Please suggest.

**Comment by xgl1999** [comment]
****
![image](https://user-images.githubusercontent.com/23210080/111867560-c8700a00-89af-11eb-87d1-80d0aa004790.png)

**Comment by FreeDooMF1** [comment]
so, what the current version? anybody knows?

**Comment by pangwa** [comment]
You can use either the master/develop branch to build from source. We have a docker image published for the iris test network, check out at [docker hub](https://hub.docker.com/r/cloverio/clover-iris).

**Comment by maxallat** [comment]
can it be that I cannot find it in the lists because 31 at the end of the testnet deleted the server?

**Comment by pangwa** [comment]
Clover now uses the release method based on git tags. Currently we relased two versions of clover (iris-*, ivy-*).  The docker images are published at docker hub: [Clover Docker Hub](https://hub.docker.com/u/cloverio). The testnet docker image could be found at [Iris Docker Image](https://hub.docker.com/r/cloverio/clover-iris/tags?page=1&ordering=last_updated). The latest version of testnet is `0.1.14`. Please checkout our documents and migration guides for later updates.
